# Generated by Django 2.2 on 2020-07-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='message', max_length=255),
            preserve_default=False,
        ),
    ]
