# Generated by Django 2.2 on 2020-07-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0005_auto_20200729_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='work_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_earned', to='log_reg_app.Work_Day'),
        ),
    ]
