# Generated by Django 2.2 on 2020-08-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0007_user_user_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_day',
            name='clock_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work_day',
            name='clock_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
